# SELECT 
# a.BOOK_ID, 
# b.AUTHOR_NAME, 
# DATE_FORMAT(a.PUBLISHED_DATE, '%Y-%M-%D') AS PUBLISHED_DATE
# FROM (SELECT BOOK_ID, AUTHOR_ID, PUBLISHED_DATE
# 	FROM BOOK
# 	WHERE CATEGORY = '경제') a, AUTHOR b
# JOIN AUTHOR ON(a.AUTHOR_ID = b.AUTHOR_ID)
# ORDER BY PUBLISHED_DATE ASC;

SELECT 
b.BOOK_ID AS BOOK_ID,
a.AUTHOR_NAME AS AUTHOR_NAME,
date_format(b.PUBLISHED_DATE, '%Y-%m-%d') AS PUBLISHED_DATE
FROM BOOK b
JOIN AUTHOR a
ON b.AUTHOR_ID = a.AUTHOR_ID
WHERE b.CATEGORY = '경제'
ORDER BY PUBLISHED_DATE
;